### ISSUE TITLE
Add date and improve weather information

### ISSUE THREAD

**Issue by hwalker928** [TowerRadioUK/StudioClock#3]

**Comment by Pukapl** [comment]
Have you considered using OpenWeather map instead of open-meto?
I've been able to reduce weather.py to a single function that only makes 1 API call instead of 2, and the response provides the weather description as a string to prevent the dictionary lookup.

**Comment by hwalker928** [comment]
> Have you considered using OpenWeather map instead of open-meto? I've been able to reduce weather.py to a single function that only makes 1 API call instead of 2, and the response provides the weather description as a string to prevent the dictionary lookup.

Feel free to commit the changes, sounds good to me if it works well

**Comment by Pukapl** [comment]
I dont think im able to create pull requests etc, [here](https://github.com/user-attachments/files/16623898/Changed.Files.zip) are the changes I made if you want to commit them.

**Comment by Pukapl** [comment]
I've commited the changes, just remember a (free) api key is required to use openweathermap, I'm happy to send you mine or you can make an account.
